/*
 * This file was generated by the Gradle "init" task.
 */

dependencies {
    implementation(project(":utils"))
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.10.3")
    implementation("joda-time:joda-time:2.9.3")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-joda:2.10.3")
    testImplementation("org.slf4j:slf4j-simple:1.7.12")
}

description = "em2m-java-sdk-simplex"

java {
    withJavadocJar()
}
